# Generated by Django 2.2.7 on 2019-11-25 11:13

from django.db import migrations, models
import pitter.models.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=pitter.models.base.default_uuid_id, editable=False, max_length=256,
                                        primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=256)),
                ('salt', models.CharField(max_length=256)),
                ('profile', models.CharField(blank=True, max_length=256)),
                ('email', models.CharField(blank=True, max_length=256)),
                ('email_notification', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
